name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    environment: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send files via SSH
        env:
          TEST: "test"
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_TARGET_DIRECTORY: ${{ secrets.SSH_TARGET_DIRECTORY }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "$TEST"
          scp -r -P 2222 ./index.html "$SSH_USER:$SSH_PASSWORD@$SSH_HOST:$SSH_TARGET_DIRECTORY"
