name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    environment: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send files via SSH
        uses: appleboy/scp-action@master
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_TARGET_DIRECTORY: ${{ secrets.SSH_TARGET_DIRECTORY }}
          SSH_USER: ${{ secrets.SSH_USER }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          source: "./index.html"
          target: ${{ secrets.SSH_TARGET_DIRECTORY }}
