name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    environment: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send files via SCP
        uses: appleboy/scp-action@master
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_TARGET_DIRECTORY: ${{ secrets.SSH_TARGET_DIRECTORY }}
          SSH_USER: ${{ secrets.SSH_USER }}
        with:
          args: "-r -P 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR ./ ${{ env.SSH_USER }}@{{ env.SSH_HOST }}:{{ env.SSH_TARGET_DIRECTORY }}"
