name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    environment: Deployment
    runs-on: ubuntu-latest
    env:
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_TARGET_DIRECTORY: ${{ secrets.SSH_TARGET_DIRECTORY }}
      SSH_USER: ${{ secrets.SSH_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SSH_USER }}
          server: ${{ secrets.SSH_HOST }}
          port: 2222
          local_path: "./*"
          remote_path: ${{ secrets.SSH_TARGET_DIRECTORY }}
          sftp_only: true
          password: ${{ secrets.SSH_PASSWORD }}
