name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    environment: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_TARGET_DIRECTORY: ${{ secrets.FTP_TARGET_DIRECTORY }}
          FTP_USER: ${{ secrets.FTP_USER }}
        with:
          username: ${{ secrets.FTP_USER }}
          server: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          local_path: "./*"
          remote_path: ${{ secrets.FTP_TARGET_DIRECTORY }}
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}
