name: Deploy

on:
  pull_request:
    branches:
      - master

env:
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_TARGET_DIRECTORY: ${{ secrets.SSH_TARGET_DIRECTORY }}
  SSH_USER: ${{ secrets.SSH_USER }}

jobs:
  deploy:
    environment: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          source: "./"
          target: ${{ secrets.SSH_TARGET_DIRECTORY }}
